name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Ruff check
        run: ruff .
      - name: Black format check
        run: black --check .
      - name: PyTest
        run: pytest
      - name: MyPy type check
        run: mypy .
